### ISSUE TITLE
The appsettings.json doesnt get copied to the output folder on dotnet publish

### ISSUE THREAD

**Issue by taherchhabra** [PioneerCode/pioneer-console-boilerplate#7]
Need to add this in the csproj file
` <None Include="app-settings.json" CopyToOutputDirectory="Always" />`

**Comment by chad-ramos** [comment]
@taherchhabra Thanks for the heads up.  Fixed, merged, and published at [nuget.org](https://www.nuget.org/packages/Pioneer.Console.Boilerplate/1.0.6)

**Comment by taherchhabra** [comment]
Awesome, and thanks for the template.
